spring:
  datasource:
    url: "jdbc:mysql://localhost/library"
    username: "root"
    password: "Gosemvhs1!"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none   #스프링이 시작할때 ENTITY의 객체와 DB의 테이블및 객체들이 서로 다를경우 어떻게 할지 정하는 라인, None 대신 CREATE >
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect